apiVersion: v1
kind: Namespace
metadata:
  name: example-preview-envs

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: example-preview-envs
imagePullSecrets:
  - name:  ghcr

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: example-preview-envs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Domain Preview Environments
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-preview-envs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    repoURL: https://github.com/cloudnativeentrepreneur/example-preview-envs.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: example-preview-envs
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true