apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
helmCharts:
- name: tempo
  releaseName: tempo
  version: 0.9.0
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml


