apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
helmCharts:
- name: external-secrets
  releaseName: external-secrets
  version: 0.6.0
  repo: https://charts.external-secrets.io
  valuesFile: values.yaml
  namespace: external-secrets