global:
  leaderElection:
    namespace: cert-manager

extraArgs:
  - --issuer-ambient-credentials

securityContext:
  enabled: true
  fsGroup: 1001

# serviceAccount:
#   annotations:
#     eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.jxRequirements.cluster.project }}:role/{{ .Values.jxRequirements.cluster.clusterName }}-cert-manager-cert-manager
#     iam.gke.io/gcp-service-account: {{ .Values.jxRequirements.cluster.clusterName }}-dn@{{ .Values.jxRequirements.cluster.project }}.iam.gserviceaccount.com
