apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
  - auth.192.168.1.10.sslip.io
  gateways:
  # - istio-system/selfsigned-tls
  - keycloak
  http:
  - route:
    - destination:
        port:
          number: 8778
        host: keycloak-http
