apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: keycloak
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - "auth.192.168.1.10.sslip.io"
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: false
