apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: aurelius-keycloak
  labels:
    app: sso
spec:
  instances: 1
  hostname: auth.192.168.1.10.sslip.io
  tlsSecret: aurelius-keycloak-tls
